[theme]
primaryColor="#f8f8ff"
backgroundColor="#e0e1dd"
secondaryBackgroundColor="#dcdcdc"
textColor="#000000"
baseFontSize=16


font = 'sans-serif'

[theme.sidebar]

primaryColor="#e0e1dd"
backgroundColor="#4d4f53"
textColor="#e98300"